# Generated by Django 4.2.2 on 2023-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_episode_episode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
