# Generated by Django 4.2.2 on 2023-07-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_favouriteanime_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anime', 'name'), ('anime', 'episode_number')},
        ),
    ]
