apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Match the size specified in your PV
  storageClassName: manual