apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Match the size specified in your PV
  storageClassName: manual