apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-db-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /backend/db