services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/api/:/backend/api/
      - ./backend/media/:/backend/media/
      - ./backend/site_copy/:/backend/site_copy

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/frontend/src
      - ./frontend/public/:/frontend/public/
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_BACKEND_IP=127.0.0.1:8000

  telegram-bot:
    build: ./telegram-bot
    depends_on: 
      - backend
    environment:
      - BACKEND_IP=172.16.0.2:8000


    