services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      # docker host volume
      - ./backend/api/:/backend/api/
      - ./backend/media/:/backend/media/
      - ./backend/site_copy/:/backend/site_copy/
      # docker persistent volume 
      - media:/backend/media
      - db:/backend/db
      
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/frontend/src
      - ./frontend/public/:/frontend/public/
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_BACKEND_IP=127.0.0.1:8000

  telegram-bot:
    build: ./telegram-bot
    depends_on: 
      - backend
    environment:
      - BACKEND_IP=backend:8000

volumes:
  media:
  db: