FROM python as build
WORKDIR ./backend
COPY ./ ./
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput

FROM nginx:1.14.2
COPY --from=build /backend /usr/share/nginx/html/backend
COPY ./nginx.conf /etc/nginx/nginx.conf 