FROM python
WORKDIR /backend
COPY ./ ./
RUN pip install -r requirements.txt
# we replaced db.sqlite3 to db/db.sqlite3; the next line is needed to prevent an error
RUN mkdir db

CMD ["bash","./start-server.sh"]