apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: ilyaviz/site-copy-frontend  
        imagePullPolicy: Always  
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_BACKEND_IP
            value: "127.0.0.1:30800"